### ISSUE TITLE
Vectorize google_geocode 

### ISSUE THREAD

**Issue by nbarsch** [SymbolixAU/googleway#153]
Hi SymbolixAU,

Is there a way to vectorize google_geocode across a vector of addresses to return lat/lon?

 (there may not be due to the google api requiring a request at a time as far as I can tell)

**Comment by SymbolixAU** [comment]
@nbarsch 

The 'one request at a time' and usage limits are sticking points.  Any 'vectorsing' will still be a loop underneath (ignoring the fact all vectorising in R is a loop at C/C++/fortran/compiled-code level)

But since users will have different API accounts with different usage rates, and different connection speeds, I can't see a reliable way of writing this loop to account for all scenarios. 

For now I'm happy to leave it as-is and let the user write the loop.

**Comment by MichaelChirico** [comment]
Probably this could be added to/emphasized in`?google_geocode`. Extra helpful would be a link to a page where you can track your usage vs. your cap.

**Comment by SymbolixAU** [comment]
@MichaelChirico I've added a section to each of the functions which call an API in [this commit](https://github.com/SymbolixAU/googleway/commit/fbe4e911574105f01fd93b596233dc9533c0b889) - is this the sort of thing you had in mind?

**Comment by MichaelChirico** [comment]
Perfect, thanks! 👍
