### ISSUE TITLE
google_places rankby

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/googleway#167]
possible bug?
https://stackoverflow.com/questions/51066940/googleway-rankby-distance-option-doesnt-work

```
set_key(read.dcf("~/Documents/.googleAPI", fields = "GOOGLE_API_KEY"))

df_places <- google_places(
	rankby = "distance",
	radar = FALSE,
	keyword = "fitness", 
  place_type = "gym",
	location = as.numeric(tram_stops[1, c("stop_lon", "stop_lat")])
	)
```

**Comment by caryshin** [comment]
Now the rankby=distance option works but I'm not longer getting the "formatted address" parameter among the results. Not sure if this is because of the rankby=distance, or if your package just doesn't use that parameter. I do see one named "vicinity", which has street address and city but it doesn't have state or zip code.

**Comment by caryshin** [comment]
Ok, turns out it just had to do with this package not having that parameter. Also, when I tried running the search with rankby="prominence", I'm getting a lot fewer results than I was with the default google way package for some reason. And when I look at the response data frames, a lot of them say "ZERO_RESULTS" for status.

**Comment by SymbolixAU** [comment]
@caryshin  "it just had to do with this package not having that parameter" - what do you mean by this package not having that parameter?

**Comment by caryshin** [comment]
I meant that your version of googleway doesn't have the formatted address parameter in the results.

**Comment by SymbolixAU** [comment]
`googleway` doesn't do anything to the results, it returns it directly from Google's API. Do you have an example of the query you're using and the result you're expecting?

**Comment by caryshin** [comment]
No matter what query I do, when i get the response I do df_places_results$formatted_address
That gives me the street address of the place, including state and zip code. But when I use your version of the package, that formatted_address parameter isn't present in the results data frame.

**Comment by caryshin** [comment]
Hold on I think I figured it out. I looked at the google places api, when you're doing a text search you get formatted address but you can't rank by distance. When you do a nearby search you can rank by distance but you get vicinity instead of formatted address in the results. So I think what happened was when you fixed the rankby distance option in your package, it switched to doing a nearby search so I no longer got formatted address but vicinity instead. I guess if I wanted to get zip codes from that I would have to re-search the name of each place in the results to get specific address data.

**Comment by SymbolixAU** [comment]
is this issue resolved now?

**Comment by caryshin** [comment]
Yes

**Comment by SymbolixAU** [comment]
you're welcome
