### ISSUE TITLE
Option to open Full Screen on different window/monitor

### ISSUE THREAD

**Issue by derekzoutendijk** [SymbolixAU/googleway#247]
Hi!

The functionality to open the map on full screen is very useful for detailed analysis of your map. I was wondering if it is possible within the limits of Shiny to open this full screen mode on a different monitor, such that you can perform actions in your app on one screen and see the effects on the map on another screen. 

I have investigated the "mwshiny" package, but that seems rather cumbersome for this use case and it seems quite difficult to enable this on published apps as well.

![googleMapsExample](https://user-images.githubusercontent.com/79793528/164235091-4c12f092-38c2-4ffe-b0ab-efc0ba0694a8.PNG)

**Comment by dcooley** [comment]
I'm sorry but I don't know much about {mwshiny}, nor how to build shiny's so that you can have multiple windows. So I don't think I can help. And I think your question is out-of-scope for {googleway}, it seems like you're after more general shiny knowledge, rather than a question specific to this package.
